# Site settings
title: StartApp
email: jordi.mateo@udl.cat
url: https://github.com/startapp-udl/startapp-udl.github.io
description: "StartAPP is an inniative to encouraging students to face a real scenario, which aims to consolidate an innovative startup based on an application for mobile devices and develop skills related to organization, communication, and human relations to coordinate the team and learn to sell the ideas."
keywords: "gtidic, teaching, innovation, udl"
skills: "Application for Mobile devices, User Expirience, Innovation in ICT, Interactive System Specification and Analysis"
meta_author: LastName FirstName

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 830051 #80B3FF
  primary-rgb: "131,0,81" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: University of Lleida
  location: Location
  teachers: Teachers
  collaborators: Collaborators

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)

teachers:
  - name: Jordi Mateo
    url: http://www.jordimateo.com
    social:
      - title: linkedin
        url: https://es.linkedin.com/in/jordi-mateo-forn%C3%A9s-84694b58
      - title: twitter
        url: https://twitter.com/MatForJordi
      - title: github
        url: https://github.com/JordiMateoUdL
  - name: Sergio Sayago
    url: https://sergiosayagoblog.wordpress.com/
    social:
      - title: linkedin
        url: https://es.linkedin.com/in/sergio-sayago-b95bb515
      - title: twitter
        url: https://twitter.com/sergiosayago


# Postal address (add as many lines as necessary)
address:
  - line: Campus Universitari Igualada-UdL

# Collaborators
collaborators:
  - name: Universitat de Lleida
    url: http://www.udl.cat
  - name: Tic Anoia
    url: http://www.ticanoia.cat


# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
